<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>

sr = 44100
kr = 4410
nchnls = 2
0dbfs =	1

instr 1	
	ipitch = 50
	ifn ftts "this is generated by festival from within sea sound", ipitch
	ao loscil 1, 1, ifn, 1
	outs ao, ao
endin

</CsInstruments>
; ==============================================
<CsScore>
i1 0 2

</CsScore>
</CsoundSynthesizer>

